name = "RectiGrids"
uuid = "8ac6971d-971d-971d-971d-971d5ab1a71A"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.1"

[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
AxisKeys = "0.1"
julia = "1.6"
