name = "LazyGrids"
uuid = "8ac6120f-0cea-45a0-84ec-ecbce27b592d"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.0"

[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"

[compat]
AxisKeys = "0.1"
julia = "1.6"
